# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64784ddb32ab957d17ab7e615ef574bad84af614e4f7a99793b66215b08bb3e183a8c9c24171db9c47e28bf53ba05de686a17c99c810614adc1423329d7b8891

test:
  secret_key_base: b393cd7048771dd15208ceb02ba645597536b83d2b0c716afd2721de9dc5878034e302348cd15af8d9dbe419a32607c1e4e8162764dc0533d421ffcca19223c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
